//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUpData
    {
        public int id { get; set; }
        public Nullable<int> lookupid { get; set; }
        public string value { get; set; }
        public Nullable<int> valueindex { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual LookUp LookUp { get; set; }
    }
}
